# Generated by Django 5.0.3 on 2024-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='transaction',
        ),
    ]
