# Generated by Django 5.0.3 on 2024-05-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_remove_notifications_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payapp.transaction'),
        ),
    ]
